package com.tushaar.miniassignment.models;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import lombok.AllArgsConstructor;
import lombok.Data;

@DynamoDBTable(tableName = "Ratings")
@Data
@AllArgsConstructor
public class MovieRating {
	
	@DynamoDBHashKey
	@DynamoDBAutoGeneratedKey
	private String id;
	@DynamoDBAttribute
	private String imdb_title_id;
	@DynamoDBAttribute
	private String title;
	@DynamoDBAttribute
	private String original;
	@DynamoDBAttribute
	private String year;
	@DynamoDBAttribute
	private String datePublished;
	@DynamoDBAttribute
	private String genre;
	@DynamoDBAttribute
	private int duration;
	@DynamoDBAttribute
	private String country;
	@DynamoDBAttribute
	private String language;
	@DynamoDBAttribute
	private String director;
	@DynamoDBAttribute
	private String writer;
	@DynamoDBAttribute
	private String production_company;
	@DynamoDBAttribute
	private String actors;
	@DynamoDBAttribute	
	private String description;
	@DynamoDBAttribute	
	private double avg_vote;
	@DynamoDBAttribute	
	private int votes;
	@DynamoDBAttribute	
	private String budget;
	@DynamoDBAttribute	
	private String usa_gross_income;
	@DynamoDBAttribute	
	private String worlwide_gross_income;
	@DynamoDBAttribute	
	private int metascore;
	@DynamoDBAttribute	
	private int reviews_from_users;
	@DynamoDBAttribute	
	private int reviews_from_critics;
	
	
	public MovieRating() {
	}


	public static MovieRating createObject(String[] data) {
		MovieRating m = new MovieRating();
		m.setImdb_title_id(data[0]);
		m.setTitle(data[1]);
		m.setOriginal(data[2]);
		m.setYear(data[3]);
		m.setDatePublished(data[4]);
		m.setGenre(data[5]);
		m.setDuration(Integer.parseInt(data[6] == "" ? "0" : data[6]));
		m.setCountry(data[7]);
		m.setLanguage(data[8]);
		m.setDirector(data[9]);
		m.setWriter(data[10]);
		m.setProduction_company(data[11]);
		m.setActors(data[12]);
		m.setDescription(data[13]);
		m.setAvg_vote(Double.parseDouble(data[14] == "" ? "0" : data[14]));
		m.setVotes(Integer.parseInt(data[15] == "" ? "0" : data[15]));
		m.setBudget(data[16]);
		m.setUsa_gross_income(data[17]);
		m.setWorlwide_gross_income(data[18]);
		m.setMetascore(Integer.parseInt(data[19] == "" ? "0" : data[19]));
		m.setReviews_from_users(Integer.parseInt(data[20] == "" ? "0" : data[20]));
		m.setReviews_from_critics(Integer.parseInt(data[21] == "" ? "0" : data[21]));
		return m;
	}
	
}
