package com.tushaar.miniassignment.models;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import lombok.AllArgsConstructor;
import lombok.Data;

@DynamoDBTable(tableName = "Ratings")
@Data
@AllArgsConstructor
public class MovieRating {
	
	@DynamoDBHashKey
	@DynamoDBAutoGeneratedKey
	private String id;
	
	@DynamoDBAttribute
	private String imdb_title_id;
	@DynamoDBAttribute
	private String title;
	@DynamoDBAttribute
	private String original;
	@DynamoDBAttribute
	private int year;
	@DynamoDBAttribute
	private String datePublished;
	@DynamoDBAttribute
	private String genre;
	@DynamoDBAttribute
	private int duration;
	@DynamoDBAttribute
	private String country;
	@DynamoDBAttribute
	private String language;
	@DynamoDBAttribute
	private String director;
	@DynamoDBAttribute
	private String writer;
	@DynamoDBAttribute
	private String production_company;
//	@DynamoDBAttribute
//	private String[] actors;
	@DynamoDBAttribute	
	private String description;
	@DynamoDBAttribute	
	private double avg_vote;
	@DynamoDBAttribute	
	private int votes;
	@DynamoDBAttribute	
	private String budget;
	@DynamoDBAttribute	
	private String usa_gross_income;
	@DynamoDBAttribute	
	private String worlwide_gross_income;
	@DynamoDBAttribute	
	private int metascore;
	@DynamoDBAttribute	
	private int reviews_from_users;
	@DynamoDBAttribute	
	private int reviews_from_critics;
	
	
	public MovieRating() {
	}
	
}
